// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp6LXqAkZoshpT8he1ivBGMqZrDtwIPwo',
    appId: '1:739830946145:web:9bc76250644548b88b0d20',
    messagingSenderId: '739830946145',
    projectId: 'contact-app-281e2',
    authDomain: 'contact-app-281e2.firebaseapp.com',
    storageBucket: 'contact-app-281e2.appspot.com',
    measurementId: 'G-0HGHV1CQH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSJ8HHqK9I07SnK7OchawGhlxV5Uw3T4M',
    appId: '1:739830946145:android:0b92495e668d4f4f8b0d20',
    messagingSenderId: '739830946145',
    projectId: 'contact-app-281e2',
    storageBucket: 'contact-app-281e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkK7FbqPjS-IHpGqvgdsIGamVhS4_MIY8',
    appId: '1:739830946145:ios:6d275cb1b76a20c78b0d20',
    messagingSenderId: '739830946145',
    projectId: 'contact-app-281e2',
    storageBucket: 'contact-app-281e2.appspot.com',
    iosClientId: '739830946145-bdhlm7bjpqk3ogs3bv4hd3ofj71ovv9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkK7FbqPjS-IHpGqvgdsIGamVhS4_MIY8',
    appId: '1:739830946145:ios:6d275cb1b76a20c78b0d20',
    messagingSenderId: '739830946145',
    projectId: 'contact-app-281e2',
    storageBucket: 'contact-app-281e2.appspot.com',
    iosClientId: '739830946145-bdhlm7bjpqk3ogs3bv4hd3ofj71ovv9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactApp',
  );
}
